"""add_product_configuration

Revision ID: 8f816b22e6f7
Revises: 1510ce09e8d1
Create Date: 2026-08-31 14:08:59.405367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f816b22e6f7'
down_revision: Union[str, None] = '1510ce09e8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('selections', sa.JSON(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_sessions_product_id'), 'configuration_sessions', ['product_id'], unique=False)
    op.create_index(op.f('ix_configuration_sessions_user_id'), 'configuration_sessions', ['user_id'], unique=False)
    op.create_table('product_configuration_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('selection_type', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_configuration_groups_id'), 'product_configuration_groups', ['id'], unique=False)
    op.create_index(op.f('ix_product_configuration_groups_product_id'), 'product_configuration_groups', ['product_id'], unique=False)
    op.create_table('product_configuration_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['product_configuration_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_configuration_options_group_id'), 'product_configuration_options', ['group_id'], unique=False)
    op.create_index(op.f('ix_product_configuration_options_id'), 'product_configuration_options', ['id'], unique=False)
    op.add_column('configuration_rules', sa.Column('source_option_id', sa.Integer(), nullable=False))
    op.add_column('configuration_rules', sa.Column('target_option_id', sa.Integer(), nullable=False))
    op.add_column('configuration_rules', sa.Column('message', sa.String(length=500), nullable=False))
    op.drop_index(op.f('ix_configuration_rules_name'), table_name='configuration_rules')
    op.create_index(op.f('ix_configuration_rules_product_id'), 'configuration_rules', ['product_id'], unique=False)
    op.create_index(op.f('ix_configuration_rules_source_option_id'), 'configuration_rules', ['source_option_id'], unique=False)
    op.create_index(op.f('ix_configuration_rules_target_option_id'), 'configuration_rules', ['target_option_id'], unique=False)
    op.drop_constraint(op.f('configuration_rules_target_product_id_fkey'), 'configuration_rules', type_='foreignkey')
    op.create_foreign_key(None, 'configuration_rules', 'product_configuration_options', ['target_option_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'configuration_rules', 'product_configuration_options', ['source_option_id'], ['id'], ondelete='CASCADE')
    op.drop_column('configuration_rules', 'target_product_id')
    op.drop_column('configuration_rules', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration_rules', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('configuration_rules', sa.Column('target_product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'configuration_rules', type_='foreignkey')
    op.drop_constraint(None, 'configuration_rules', type_='foreignkey')
    op.create_foreign_key(op.f('configuration_rules_target_product_id_fkey'), 'configuration_rules', 'products', ['target_product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_configuration_rules_target_option_id'), table_name='configuration_rules')
    op.drop_index(op.f('ix_configuration_rules_source_option_id'), table_name='configuration_rules')
    op.drop_index(op.f('ix_configuration_rules_product_id'), table_name='configuration_rules')
    op.create_index(op.f('ix_configuration_rules_name'), 'configuration_rules', ['name'], unique=True)
    op.drop_column('configuration_rules', 'message')
    op.drop_column('configuration_rules', 'target_option_id')
    op.drop_column('configuration_rules', 'source_option_id')
    op.drop_index(op.f('ix_product_configuration_options_id'), table_name='product_configuration_options')
    op.drop_index(op.f('ix_product_configuration_options_group_id'), table_name='product_configuration_options')
    op.drop_table('product_configuration_options')
    op.drop_index(op.f('ix_product_configuration_groups_product_id'), table_name='product_configuration_groups')
    op.drop_index(op.f('ix_product_configuration_groups_id'), table_name='product_configuration_groups')
    op.drop_table('product_configuration_groups')
    op.drop_index(op.f('ix_configuration_sessions_user_id'), table_name='configuration_sessions')
    op.drop_index(op.f('ix_configuration_sessions_product_id'), table_name='configuration_sessions')
    op.drop_table('configuration_sessions')
    # ### end Alembic commands ###
