"""add_product_pricing_tiers

Revision ID: 9e56a94687c9
Revises: a67fed2fe955
Create Date: 2026-08-30 18:15:27.153079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e56a94687c9'
down_revision: Union[str, None] = 'a67fed2fe955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_pricing_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pricing_method', sa.String(length=50), nullable=False),
    sa.Column('tiered_mode', sa.String(length=50), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_pricing_tiers_id'), 'product_pricing_tiers', ['id'], unique=False)
    op.create_index(op.f('ix_product_pricing_tiers_product_id'), 'product_pricing_tiers', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_pricing_tiers_product_id'), table_name='product_pricing_tiers')
    op.drop_index(op.f('ix_product_pricing_tiers_id'), table_name='product_pricing_tiers')
    op.drop_table('product_pricing_tiers')
    # ### end Alembic commands ###
