"""add_configuration_versioning

Revision ID: 9e57e5256df4
Revises: eda6c581e7c5
Create Date: 2026-08-31 14:22:48.552884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e57e5256df4'
down_revision: Union[str, None] = 'eda6c581e7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('change_summary', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_versions_entity_id'), 'configuration_versions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_configuration_versions_id'), 'configuration_versions', ['id'], unique=False)
    op.add_column('bundle_components', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bundle_components_version_id'), 'bundle_components', ['version_id'], unique=False)
    op.create_foreign_key(None, 'bundle_components', 'configuration_versions', ['version_id'], ['id'], ondelete='SET NULL')
    op.add_column('bundle_configuration_sessions', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bundle_configuration_sessions_version_id'), 'bundle_configuration_sessions', ['version_id'], unique=False)
    op.create_foreign_key(None, 'bundle_configuration_sessions', 'configuration_versions', ['version_id'], ['id'], ondelete='SET NULL')
    op.add_column('configuration_rules', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_configuration_rules_version_id'), 'configuration_rules', ['version_id'], unique=False)
    op.create_foreign_key(None, 'configuration_rules', 'configuration_versions', ['version_id'], ['id'], ondelete='SET NULL')
    op.add_column('configuration_sessions', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_configuration_sessions_version_id'), 'configuration_sessions', ['version_id'], unique=False)
    op.create_foreign_key(None, 'configuration_sessions', 'configuration_versions', ['version_id'], ['id'], ondelete='SET NULL')
    op.add_column('product_configuration_groups', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_configuration_groups_version_id'), 'product_configuration_groups', ['version_id'], unique=False)
    op.create_foreign_key(None, 'product_configuration_groups', 'configuration_versions', ['version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_configuration_groups', type_='foreignkey')
    op.drop_index(op.f('ix_product_configuration_groups_version_id'), table_name='product_configuration_groups')
    op.drop_column('product_configuration_groups', 'version_id')
    op.drop_constraint(None, 'configuration_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_configuration_sessions_version_id'), table_name='configuration_sessions')
    op.drop_column('configuration_sessions', 'version_id')
    op.drop_constraint(None, 'configuration_rules', type_='foreignkey')
    op.drop_index(op.f('ix_configuration_rules_version_id'), table_name='configuration_rules')
    op.drop_column('configuration_rules', 'version_id')
    op.drop_constraint(None, 'bundle_configuration_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_bundle_configuration_sessions_version_id'), table_name='bundle_configuration_sessions')
    op.drop_column('bundle_configuration_sessions', 'version_id')
    op.drop_constraint(None, 'bundle_components', type_='foreignkey')
    op.drop_index(op.f('ix_bundle_components_version_id'), table_name='bundle_components')
    op.drop_column('bundle_components', 'version_id')
    op.drop_index(op.f('ix_configuration_versions_id'), table_name='configuration_versions')
    op.drop_index(op.f('ix_configuration_versions_entity_id'), table_name='configuration_versions')
    op.drop_table('configuration_versions')
    # ### end Alembic commands ###
