"""add_product_pricing_settings

Revision ID: b97fc420a234
Revises: 9e56a94687c9
Create Date: 2026-08-30 18:21:06.670029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97fc420a234'
down_revision: Union[str, None] = '9e56a94687c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_pricing_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pricing_method', sa.String(length=50), nullable=False),
    sa.Column('markup_percent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_pricing_settings_id'), 'product_pricing_settings', ['id'], unique=False)
    op.create_index(op.f('ix_product_pricing_settings_product_id'), 'product_pricing_settings', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_pricing_settings_product_id'), table_name='product_pricing_settings')
    op.drop_index(op.f('ix_product_pricing_settings_id'), table_name='product_pricing_settings')
    op.drop_table('product_pricing_settings')
    # ### end Alembic commands ###
