"""add_product_bundles

Revision ID: eda6c581e7c5
Revises: 8f816b22e6f7
Create Date: 2026-08-31 14:15:24.592112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda6c581e7c5'
down_revision: Union[str, None] = '8f816b22e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundles_id'), 'bundles', ['id'], unique=False)
    op.create_index(op.f('ix_bundles_sku'), 'bundles', ['sku'], unique=True)
    op.create_table('bundle_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_audit_logs_bundle_id'), 'bundle_audit_logs', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_bundle_audit_logs_id'), 'bundle_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_bundle_audit_logs_user_id'), 'bundle_audit_logs', ['user_id'], unique=False)
    op.create_table('bundle_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('default_selected', sa.Boolean(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('default_quantity', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_components_bundle_id'), 'bundle_components', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_bundle_components_id'), 'bundle_components', ['id'], unique=False)
    op.create_index(op.f('ix_bundle_components_product_id'), 'bundle_components', ['product_id'], unique=False)
    op.create_table('bundle_configuration_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('selections', sa.JSON(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_configuration_sessions_bundle_id'), 'bundle_configuration_sessions', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_bundle_configuration_sessions_user_id'), 'bundle_configuration_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bundle_configuration_sessions_user_id'), table_name='bundle_configuration_sessions')
    op.drop_index(op.f('ix_bundle_configuration_sessions_bundle_id'), table_name='bundle_configuration_sessions')
    op.drop_table('bundle_configuration_sessions')
    op.drop_index(op.f('ix_bundle_components_product_id'), table_name='bundle_components')
    op.drop_index(op.f('ix_bundle_components_id'), table_name='bundle_components')
    op.drop_index(op.f('ix_bundle_components_bundle_id'), table_name='bundle_components')
    op.drop_table('bundle_components')
    op.drop_index(op.f('ix_bundle_audit_logs_user_id'), table_name='bundle_audit_logs')
    op.drop_index(op.f('ix_bundle_audit_logs_id'), table_name='bundle_audit_logs')
    op.drop_index(op.f('ix_bundle_audit_logs_bundle_id'), table_name='bundle_audit_logs')
    op.drop_table('bundle_audit_logs')
    op.drop_index(op.f('ix_bundles_sku'), table_name='bundles')
    op.drop_index(op.f('ix_bundles_id'), table_name='bundles')
    op.drop_table('bundles')
    # ### end Alembic commands ###
